import os
import shutil
from pathlib import Path

OUTPUT_DIR = Path("../output")

# ---------------------------------------------------------
# Funciones auxiliares
# ---------------------------------------------------------
def clean_output():
    """
    Remove only the files and folders generated by convert.py and split.py.
    """
    if not OUTPUT_DIR.exists():
        print("Output directory does not exist.")
        return

    # Archivos generados por convert.py
    article_md = OUTPUT_DIR / "article.md"
    headers_log = OUTPUT_DIR / "headers.log"

    # Archivos generados por split.py
    readme_md = OUTPUT_DIR / "README.md"
    split_log = OUTPUT_DIR / "split.log"

    # Carpeta generada por split.py
    articles_dir = OUTPUT_DIR / "articles"

    targets = [
        article_md,
        headers_log,
        readme_md,
        split_log,
    ]

    # Borrar archivos específicos
    for file in targets:
        if file.exists() and file.is_file():
            try:
                file.unlink()
                print(f"Deleted file: {file}")
            except Exception as e:
                print(f"Error deleting {file}: {e}")

    # Borrar carpeta articles/
    if articles_dir.exists() and articles_dir.is_dir():
        try:
            shutil.rmtree(articles_dir)
            print(f"Deleted directory: {articles_dir}")
        except Exception as e:
            print(f"Error deleting directory {articles_dir}: {e}")

    print("Output directory cleaned successfully.")


# ---------------------------------------------------------
# Entry point
# ---------------------------------------------------------
# Ejecución directa del proceso de limpieza.

if __name__ == "__main__":
    clean_output()
